### PR TITLE
docs: Fix missing setup instructions

### PR DESCRIPTION
**Pull request by joeyparrish**
Nowhere in the README or the bridge data template did it mention that the worker names needed to be unique.  However, using the default names led to the error "Wrong credentials to submit as this worker."  I found the cause on Reddit.

This adds brief notes to both the README and the template file to try to guide people explicitly on this point.  Had these notes been present, I would not have made the mistake of keeping the defaults.

### CODE REVIEW

**Comment by oceanmasterza** [comment]
Nowhere do the instructions explain that you first need python and pip
either. If this is really going to take of with mainstream then an
installer should take care of it.

**Review by tazlin — APPROVED** [review]
I've tried to clarify the intent behind your original changes, including highlighting the dynamics in both the readme and logs as well.

**Comment by tazlin** [comment]
> Nowhere in the README or the bridge data template did it mention that the worker names needed to be unique. However, using the default names led to the error "Wrong credentials to submit as this worker." I found the cause on Reddit.
> 
> This adds brief notes to both the README and the template file to try to guide people explicitly on this point. Had these notes been present, I would not have made the mistake of keeping the defaults.

Thanks for taking the initiative to open an PR. Its plain to see that this is confusing behavior, so the change is welcome.

**Comment by tazlin** [comment]
@oceanmasterza 
> Nowhere do the instructions explain that you first need python and pip either. If this is really going to take of with mainstream then an installer should take care of it.

Your situation was highly specific and we put a great deal of effort into trying to make it easier for you. However, please note that there is no requirement to already have python on machine, and that there is an installer for both [windows](https://github.com/Haidra-Org/horde-worker-reGen/blob/main/update-runtime.cmd) and [linux](https://github.com/Haidra-Org/horde-worker-reGen/blob/main/update-runtime.sh) and even [AMD/RoCm](https://github.com/Haidra-Org/horde-worker-reGen/blob/main/update-runtime-rocm.sh) that does in fact handle installing everything required. 

In the specific cases that you would need to install python, as [mentioned in the main docs](https://github.com/Haidra-Org/horde-worker-reGen#updating-runtime) and [explained here](https://github.com/Haidra-Org/horde-worker-reGen/blob/main/README_advanced.md#advanced-users-local-install), we **do** explain that you need python first.

If you have any further specific problems, or if you feel the docs are still insufficient, feel free to open an issue with a more specific request.

**Pull request merged**
