### PR TITLE
rocm version via index url

### PR DESCRIPTION
**Pull request by HPPinata**
--extra-index-url https://download.pytorch.org/whl/rocmX.Y is sufficient to install the right package.
This also makes A/B version testing easier.

### CODE REVIEW

**Comment by tazlin** [comment]
You did bring to my attention that the [files did not match](#314). However, you could practically get the same convenience that I think you're trying to bring to this file by using the main `requirements.txt` instead. It is supposed to be otherwise identical and I foresee that remaining to be the case. 

The purpose of the rocm tag in this file is more to help avoid the pitfall of accidently installing the cpu or CUDA version of torch when using AMD. In fact, the existence of the `requirements.rocm.txt` file dates back to a time where you would have had to have had installed it manually via the command line.

There might be something I'm missing here. If you still think its worth adding, let me know why.

**Comment by HPPinata** [comment]
I just stumbled across this when trying to A/B test different ROCm versions.

With the explicit version tag removed this can be done exclusively in the Dockerfile building the environment.
If it's part of the `requirements.txt` I have to point the build to my fork.

I haven't looked at whether it "just works" with the standard `requirements.txt` but will test that shortly.

This isn't really too relevant (the fork exists now, might as well use it), just a bit annoying and a potentially unified `requirements.txt` might be a cleaner solution if it actually ends up working out.

**Comment by tazlin** [comment]
Yea, as it is, the rocm reqs file is more of a legacy artifact from when support was experimental. Maybe it should be unified sooner than later.

**Comment by tazlin** [comment]
In any order of your choosing regarding the other pending PRs by you and me, please rebase this PR at some point and I will include it in `raw-png`.

**Comment by HPPinata** [comment]
@tazlin this is also ready to be merged

**Pull request merged**
